---
site_name: '${{values.app_name}}'
site_description: 'Documentation for ${{values.app_name}}'
repo_url: https://github.com/laz-rb/${{values.app_name}}
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting started: 'index.md'
